
CREATE TABLE QUESTION1
(
  ANSWER_KEY int          NOT NULL COMMENT 'First key',
  ANSWER     varchar(200) NULL    ,
  PRIMARY KEY (ANSWER_KEY)
) COMMENT '답항';

CREATE TABLE QUESTIONS
(
  ID        int NOT NULL COMMENT 'unique key',
  Question1 int NOT NULL COMMENT '답항 key',
  Question2 int NOT NULL COMMENT '답항 key',
  Question3 int NOT NULL COMMENT '답항 key',
  Question4 int NOT NULL COMMENT '답항 key'
) COMMENT '질문';

CREATE TABLE SURVEYEE
(
  ID   int          NOT NULL COMMENT 'unique key',
  NAME varchar(200) NULL     COMMENT '피조사자 이름',
  PRIMARY KEY (ID)
) COMMENT '피조사자';

ALTER TABLE QUESTIONS
  ADD CONSTRAINT FK_SURVEYEE_TO_QUESTIONS
    FOREIGN KEY (ID)
    REFERENCES SURVEYEE (ID);

ALTER TABLE QUESTIONS
  ADD CONSTRAINT FK_QUESTION1_TO_QUESTIONS
    FOREIGN KEY (Question1)
    REFERENCES QUESTION1 (ANSWER_KEY);

ALTER TABLE QUESTIONS
  ADD CONSTRAINT FK_QUESTION_TO_QUESTIONS1
    FOREIGN KEY (Question2)
    REFERENCES QUESTION1 (ANSWER_KEY);

ALTER TABLE QUESTIONS
  ADD CONSTRAINT FK_QUESTION_TO_QUESTIONS2
    FOREIGN KEY (Question3)
    REFERENCES QUESTION1 (ANSWER_KEY);

ALTER TABLE QUESTIONS
  ADD CONSTRAINT FK_QUESTION_TO_QUESTIONS3
    FOREIGN KEY (Question4)
    REFERENCES QUESTION1 (ANSWER_KEY);
